// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:16a3e1a7-add4-4bc2-baf7-0c3b39cea424",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zomJGdbtE",
    "aws_user_pools_web_client_id": "1urmt2v90tm59mje7m68venjh9",
    "oauth": {}
};


export default awsmobile;
